resources:
- deployment.yaml
- service.yaml

# commonLabels:
#   app: kustomwebapp
labels:
  - pairs:
      app: kustomwebapp
    includeSelectors: true 
    includeTemplates: true 

commonAnnotations:
  app: mykustom-annontations

namePrefix:
  kustom-

nameSuffix:
  -v1